* src/harness/vm_tables.s -- GENERATED by harness/tools/gen_vm_tables.py. DO NOT EDIT.
*
* ★★★ Generated from tools/agivm/optable.py, which is itself generated from the pinned oracle
* by gen_oracle_tables.py. Editing this file by hand breaks that chain, and the chain is the
* only reason the constants are trusted: state.py records four wrong VM_VAR/VM_FLAG values and
* an entirely reversed ViewFlags assignment from the one time they were typed by hand.
*
* ★ Regenerate:  python harness/tools/gen_vm_tables.py --out src/harness/vm_tables.s
* ★ Drift check: python harness/tools/gen_vm_tables.py --check
*
* source: V2_TESTS 20 entries, V2_COMMANDS 183 entries


* ── VMOP_ARGS: argument bytes per command opcode ──────────────────
* ★ ScummVM: parameterSize = strlen(parameters). Every parameter is one byte.
VMOP_ARGS:
                fcb     $00,$01,$01,$02,$02,$02,$02,$02,$02,$02,$02,$02,$01,$01,$01,$01        ; 00-0F
                fcb     $01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$00,$01,$01,$00,$01,$01        ; 10-1F
                fcb     $01,$01,$00,$01,$01,$03,$03,$03,$03,$02,$02,$02,$02,$01,$01,$02        ; 20-2F
                fcb     $02,$02,$02,$02,$02,$02,$02,$02,$01,$02,$01,$01,$01,$01,$01,$01        ; 30-3F
                fcb     $01,$01,$01,$01,$01,$03,$01,$01,$01,$02,$01,$02,$02,$01,$01,$02        ; 40-4F
                fcb     $02,$05,$05,$03,$01,$01,$02,$02,$01,$01,$04,$00,$01,$01,$01,$02        ; 50-5F
                fcb     $02,$02,$01,$02,$00,$01,$01,$03,$03,$03,$00,$00,$01,$02,$01,$03        ; 60-6F
                fcb     $00,$00,$02,$05,$02,$01,$02,$00,$00,$03,$07,$07,$00,$00,$00,$00        ; 70-7F
                fcb     $00,$01,$03,$00,$00,$01,$01,$00,$00,$00,$00,$00,$00,$00,$01,$01        ; 80-8F
                fcb     $01,$00,$00,$03,$03,$00,$03,$04,$04,$01,$05,$02,$01,$02,$00,$01        ; 90-9F
                fcb     $01,$00,$01,$00,$00,$02,$02,$02,$02,$00,$01,$00,$00,$00,$01,$01        ; A0-AF
                fcb     $00,$01,$00,$04,$02,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; B0-BF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; C0-CF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; D0-DF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; E0-EF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; F0-FF

* -- VMTEST_ARGS: operand bytes per TEST opcode --------------------
* * vm_skip_instruction steps ip by this after a test runs. Duplicating
* these lengths in the assembly would be a second place to drift.
VMTEST_ARGS:
                fcb     $00,$02,$02,$02,$02,$02,$02,$01,$01,$01,$02,$05,$01,$00,$00,$02        ; 00-0F
                fcb     $05,$05,$05,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 10-1F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 20-2F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 30-3F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 40-4F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 50-5F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 60-6F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 70-7F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 80-8F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; 90-9F
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; A0-AF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; B0-BF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; C0-CF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; D0-DF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; E0-EF
                fcb     $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00        ; F0-FF

* ── VMOP_TAB: handler per command opcode ──────────────────────────
* ★★ Unimplemented entries point at vm_op_unimpl, which HALTS with the opcode
* number. AC-5 forbids a silent no-op: it would desynchronise nothing and
* diverge everything, so the diff would name a symptom, never the cause.
VMOP_TAB:
                fdb     vm_op_return            ; 00 return
                fdb     vm_op_unimpl            ; 01 increment(v)
                fdb     vm_op_unimpl            ; 02 decrement(v)
                fdb     vm_op_unimpl            ; 03 assignn(vn)
                fdb     vm_op_unimpl            ; 04 assignv(vv)
                fdb     vm_op_unimpl            ; 05 addn(vn)
                fdb     vm_op_unimpl            ; 06 addv(vv)
                fdb     vm_op_unimpl            ; 07 subn(vn)
                fdb     vm_op_unimpl            ; 08 subv(vv)
                fdb     vm_op_unimpl            ; 09 lindirectv(vv)
                fdb     vm_op_unimpl            ; 0A lindirect(vv)
                fdb     vm_op_unimpl            ; 0B lindirectn(vn)
                fdb     vm_op_unimpl            ; 0C set(n)
                fdb     vm_op_unimpl            ; 0D reset(n)
                fdb     vm_op_unimpl            ; 0E toggle(n)
                fdb     vm_op_unimpl            ; 0F set.v(v)
                fdb     vm_op_unimpl            ; 10 reset.v(v)
                fdb     vm_op_unimpl            ; 11 toggle.v(v)
                fdb     vm_op_unimpl            ; 12 new.room(n)
                fdb     vm_op_unimpl            ; 13 new.room.v(v)
                fdb     vm_op_unimpl            ; 14 load.logics(n)
                fdb     vm_op_unimpl            ; 15 load.logics.v(v)
                fdb     vm_op_unimpl            ; 16 call(n)
                fdb     vm_op_unimpl            ; 17 call.v(v)
                fdb     vm_op_unimpl            ; 18 load.pic(v)
                fdb     vm_op_modelled          ; 19 draw.pic(v)  [modelled]
                fdb     vm_op_modelled          ; 1A show.pic()  [modelled]
                fdb     vm_op_unimpl            ; 1B discard.pic(v)
                fdb     vm_op_modelled          ; 1C overlay.pic(v)  [modelled]
                fdb     vm_op_modelled          ; 1D show.pri.screen()  [modelled]
                fdb     vm_op_unimpl            ; 1E load.view(n)
                fdb     vm_op_unimpl            ; 1F load.view.v(v)
                fdb     vm_op_unimpl            ; 20 discard.view(n)
                fdb     vm_op_unimpl            ; 21 animate.obj(n)
                fdb     vm_op_unimpl            ; 22 unanimate.all()
                fdb     vm_op_unimpl            ; 23 draw(n)
                fdb     vm_op_unimpl            ; 24 erase(n)
                fdb     vm_op_unimpl            ; 25 position(nnn)
                fdb     vm_op_unimpl            ; 26 position.v(nvv)
                fdb     vm_op_unimpl            ; 27 get.posn(nvv)
                fdb     vm_op_unimpl            ; 28 reposition(nvv)
                fdb     vm_op_unimpl            ; 29 set.view(nn)
                fdb     vm_op_unimpl            ; 2A set.view.v(nv)
                fdb     vm_op_unimpl            ; 2B set.loop(nn)
                fdb     vm_op_unimpl            ; 2C set.loop.v(nv)
                fdb     vm_op_unimpl            ; 2D fix.loop(n)
                fdb     vm_op_unimpl            ; 2E release.loop(n)
                fdb     vm_op_unimpl            ; 2F set.cel(nn)
                fdb     vm_op_unimpl            ; 30 set.cel.v(nv)
                fdb     vm_op_unimpl            ; 31 last.cel(nv)
                fdb     vm_op_unimpl            ; 32 current.cel(nv)
                fdb     vm_op_unimpl            ; 33 current.loop(nv)
                fdb     vm_op_unimpl            ; 34 current.view(nv)
                fdb     vm_op_unimpl            ; 35 number.of.loops(nv)
                fdb     vm_op_unimpl            ; 36 set.priority(nn)
                fdb     vm_op_unimpl            ; 37 set.priority.v(nv)
                fdb     vm_op_unimpl            ; 38 release.priority(n)
                fdb     vm_op_unimpl            ; 39 get.priority(nn)
                fdb     vm_op_unimpl            ; 3A stop.update(n)
                fdb     vm_op_unimpl            ; 3B start.update(n)
                fdb     vm_op_unimpl            ; 3C force.update(n)
                fdb     vm_op_unimpl            ; 3D ignore.horizon(n)
                fdb     vm_op_unimpl            ; 3E observe.horizon(n)
                fdb     vm_op_unimpl            ; 3F set.horizon(n)
                fdb     vm_op_unimpl            ; 40 object.on.water(n)
                fdb     vm_op_unimpl            ; 41 object.on.land(n)
                fdb     vm_op_unimpl            ; 42 object.on.anything(n)
                fdb     vm_op_unimpl            ; 43 ignore.objs(n)
                fdb     vm_op_unimpl            ; 44 observe.objs(n)
                fdb     vm_op_unimpl            ; 45 distance(nnv)
                fdb     vm_op_unimpl            ; 46 stop.cycling(n)
                fdb     vm_op_unimpl            ; 47 start.cycling(n)
                fdb     vm_op_unimpl            ; 48 normal.cycle(n)
                fdb     vm_op_unimpl            ; 49 end.of.loop(nn)
                fdb     vm_op_unimpl            ; 4A reverse.cycle(n)
                fdb     vm_op_unimpl            ; 4B reverse.loop(nn)
                fdb     vm_op_unimpl            ; 4C cycle.time(nv)
                fdb     vm_op_unimpl            ; 4D stop.motion(n)
                fdb     vm_op_unimpl            ; 4E start.motion(n)
                fdb     vm_op_unimpl            ; 4F step.size(nv)
                fdb     vm_op_unimpl            ; 50 step.time(nv)
                fdb     vm_op_unimpl            ; 51 move.obj(nnnnn)
                fdb     vm_op_unimpl            ; 52 move.obj.v(nvvvv)
                fdb     vm_op_unimpl            ; 53 follow.ego(nnn)
                fdb     vm_op_unimpl            ; 54 wander(n)
                fdb     vm_op_unimpl            ; 55 normal.motion(n)
                fdb     vm_op_unimpl            ; 56 set.dir(nv)
                fdb     vm_op_unimpl            ; 57 get.dir(nv)
                fdb     vm_op_unimpl            ; 58 ignore.blocks(n)
                fdb     vm_op_unimpl            ; 59 observe.blocks(n)
                fdb     vm_op_unimpl            ; 5A block(nnnn)
                fdb     vm_op_unimpl            ; 5B unblock()
                fdb     vm_op_unimpl            ; 5C get(n)
                fdb     vm_op_unimpl            ; 5D get.v(v)
                fdb     vm_op_unimpl            ; 5E drop(n)
                fdb     vm_op_unimpl            ; 5F put(nn)
                fdb     vm_op_unimpl            ; 60 put.v(vv)
                fdb     vm_op_unimpl            ; 61 get.room.v(vv)
                fdb     vm_op_modelled          ; 62 load.sound(n)  [modelled]
                fdb     vm_op_modelled          ; 63 sound(nn)  [modelled]
                fdb     vm_op_modelled          ; 64 stop.sound()  [modelled]
                fdb     vm_op_modelled          ; 65 print(s)  [modelled]
                fdb     vm_op_modelled          ; 66 print.v(v)  [modelled]
                fdb     vm_op_modelled          ; 67 display(nns)  [modelled]
                fdb     vm_op_modelled          ; 68 display.v(vvv)  [modelled]
                fdb     vm_op_modelled          ; 69 clear.lines(nns)  [modelled]
                fdb     vm_op_unimpl            ; 6A text.screen()
                fdb     vm_op_unimpl            ; 6B graphics()
                fdb     vm_op_modelled          ; 6C set.cursor.char(s)  [modelled]
                fdb     vm_op_modelled          ; 6D set.text.attribute(nn)  [modelled]
                fdb     vm_op_modelled          ; 6E shake.screen(n)  [modelled]
                fdb     vm_op_modelled          ; 6F configure.screen(nnn)  [modelled]
                fdb     vm_op_modelled          ; 70 status.line.on()  [modelled]
                fdb     vm_op_modelled          ; 71 status.line.off()  [modelled]
                fdb     vm_op_unimpl            ; 72 set.string(ns)
                fdb     vm_op_unimpl            ; 73 get.string(nsnnn)
                fdb     vm_op_unimpl            ; 74 word.to.string(nn)
                fdb     vm_op_unimpl            ; 75 parse(n)
                fdb     vm_op_unimpl            ; 76 get.num(nv)
                fdb     vm_op_modelled          ; 77 prevent.input()  [modelled]
                fdb     vm_op_modelled          ; 78 accept.input()  [modelled]
                fdb     vm_op_modelled          ; 79 set.key(nnn)  [modelled]
                fdb     vm_op_modelled          ; 7A add.to.pic(nnnnnnn)  [modelled]
                fdb     vm_op_modelled          ; 7B add.to.pic.v(vvvvvvv)  [modelled]
                fdb     vm_op_modelled          ; 7C status()  [modelled]
                fdb     vm_op_unimpl            ; 7D save.game()
                fdb     vm_op_unimpl            ; 7E restore.game()
                fdb     vm_op_modelled          ; 7F init.disk()  [modelled]
                fdb     vm_op_unimpl            ; 80 restart.game()
                fdb     vm_op_modelled          ; 81 show.obj(n)  [modelled]
                fdb     vm_op_unimpl            ; 82 random(nnv)
                fdb     vm_op_unimpl            ; 83 program.control()
                fdb     vm_op_unimpl            ; 84 player.control()
                fdb     vm_op_modelled          ; 85 obj.status.v(v)  [modelled]
                fdb     vm_op_unimpl            ; 86 quit(n)
                fdb     vm_op_modelled          ; 87 show.mem()  [modelled]
                fdb     vm_op_modelled          ; 88 pause()  [modelled]
                fdb     vm_op_modelled          ; 89 echo.line()  [modelled]
                fdb     vm_op_modelled          ; 8A cancel.line()  [modelled]
                fdb     vm_op_modelled          ; 8B init.joy()  [modelled]
                fdb     vm_op_modelled          ; 8C toggle.monitor()  [modelled]
                fdb     vm_op_modelled          ; 8D version()  [modelled]
                fdb     vm_op_modelled          ; 8E script.size(n)  [modelled]
                fdb     vm_op_modelled          ; 8F set.game.id(s)  [modelled]
                fdb     vm_op_modelled          ; 90 log(s)  [modelled]
                fdb     vm_op_modelled          ; 91 set.scan.start()  [modelled]
                fdb     vm_op_modelled          ; 92 reset.scan.start()  [modelled]
                fdb     vm_op_unimpl            ; 93 reposition.to(nnn)
                fdb     vm_op_unimpl            ; 94 reposition.to.v(nvv)
                fdb     vm_op_modelled          ; 95 trace.on()  [modelled]
                fdb     vm_op_modelled          ; 96 trace.info(nnn)  [modelled]
                fdb     vm_op_modelled          ; 97 print.at(snnn)  [modelled]
                fdb     vm_op_modelled          ; 98 print.at.v(vnnn)  [modelled]
                fdb     vm_op_unimpl            ; 99 discard.view.v(v)
                fdb     vm_op_modelled          ; 9A clear.text.rect(nnnnn)  [modelled]
                fdb     vm_op_modelled          ; 9B set.upper.left(nn)  [modelled]
                fdb     vm_op_modelled          ; 9C set.menu(s)  [modelled]
                fdb     vm_op_modelled          ; 9D set.menu.item(sn)  [modelled]
                fdb     vm_op_modelled          ; 9E submit.menu()  [modelled]
                fdb     vm_op_modelled          ; 9F enable.item(n)  [modelled]
                fdb     vm_op_modelled          ; A0 disable.item(n)  [modelled]
                fdb     vm_op_modelled          ; A1 menu.input()  [modelled]
                fdb     vm_op_modelled          ; A2 show.obj.v(v)  [modelled]
                fdb     vm_op_modelled          ; A3 open.dialogue()  [modelled]
                fdb     vm_op_modelled          ; A4 close.dialogue()  [modelled]
                fdb     vm_op_unimpl            ; A5 mul.n(vn)
                fdb     vm_op_unimpl            ; A6 mul.v(vv)
                fdb     vm_op_unimpl            ; A7 div.n(vn)
                fdb     vm_op_unimpl            ; A8 div.v(vv)
                fdb     vm_op_modelled          ; A9 close.window()  [modelled]
                fdb     vm_op_modelled          ; AA set.simple(n)  [modelled]
                fdb     vm_op_modelled          ; AB push.script()  [modelled]
                fdb     vm_op_modelled          ; AC pop.script()  [modelled]
                fdb     vm_op_modelled          ; AD hold.key()  [modelled]
                fdb     vm_op_modelled          ; AE set.pri.base(n)  [modelled]
                fdb     vm_op_modelled          ; AF discard.sound(n)  [modelled]
                fdb     vm_op_modelled          ; B0 hide.mouse()  [modelled]
                fdb     vm_op_modelled          ; B1 allow.menu(n)  [modelled]
                fdb     vm_op_modelled          ; B2 show.mouse()  [modelled]
                fdb     vm_op_modelled          ; B3 fence.mouse(nnnn)  [modelled]
                fdb     vm_op_modelled          ; B4 get.mse.posn(vv)  [modelled]
                fdb     vm_op_modelled          ; B5 release.key()  [modelled]
                fdb     vm_op_modelled          ; B6 adj.ego.move.to.x.y()  [modelled]
                fdb     vm_op_unimpl            ; B7 --
                fdb     vm_op_unimpl            ; B8 --
                fdb     vm_op_unimpl            ; B9 --
                fdb     vm_op_unimpl            ; BA --
                fdb     vm_op_unimpl            ; BB --
                fdb     vm_op_unimpl            ; BC --
                fdb     vm_op_unimpl            ; BD --
                fdb     vm_op_unimpl            ; BE --
                fdb     vm_op_unimpl            ; BF --
                fdb     vm_op_unimpl            ; C0 --
                fdb     vm_op_unimpl            ; C1 --
                fdb     vm_op_unimpl            ; C2 --
                fdb     vm_op_unimpl            ; C3 --
                fdb     vm_op_unimpl            ; C4 --
                fdb     vm_op_unimpl            ; C5 --
                fdb     vm_op_unimpl            ; C6 --
                fdb     vm_op_unimpl            ; C7 --
                fdb     vm_op_unimpl            ; C8 --
                fdb     vm_op_unimpl            ; C9 --
                fdb     vm_op_unimpl            ; CA --
                fdb     vm_op_unimpl            ; CB --
                fdb     vm_op_unimpl            ; CC --
                fdb     vm_op_unimpl            ; CD --
                fdb     vm_op_unimpl            ; CE --
                fdb     vm_op_unimpl            ; CF --
                fdb     vm_op_unimpl            ; D0 --
                fdb     vm_op_unimpl            ; D1 --
                fdb     vm_op_unimpl            ; D2 --
                fdb     vm_op_unimpl            ; D3 --
                fdb     vm_op_unimpl            ; D4 --
                fdb     vm_op_unimpl            ; D5 --
                fdb     vm_op_unimpl            ; D6 --
                fdb     vm_op_unimpl            ; D7 --
                fdb     vm_op_unimpl            ; D8 --
                fdb     vm_op_unimpl            ; D9 --
                fdb     vm_op_unimpl            ; DA --
                fdb     vm_op_unimpl            ; DB --
                fdb     vm_op_unimpl            ; DC --
                fdb     vm_op_unimpl            ; DD --
                fdb     vm_op_unimpl            ; DE --
                fdb     vm_op_unimpl            ; DF --
                fdb     vm_op_unimpl            ; E0 --
                fdb     vm_op_unimpl            ; E1 --
                fdb     vm_op_unimpl            ; E2 --
                fdb     vm_op_unimpl            ; E3 --
                fdb     vm_op_unimpl            ; E4 --
                fdb     vm_op_unimpl            ; E5 --
                fdb     vm_op_unimpl            ; E6 --
                fdb     vm_op_unimpl            ; E7 --
                fdb     vm_op_unimpl            ; E8 --
                fdb     vm_op_unimpl            ; E9 --
                fdb     vm_op_unimpl            ; EA --
                fdb     vm_op_unimpl            ; EB --
                fdb     vm_op_unimpl            ; EC --
                fdb     vm_op_unimpl            ; ED --
                fdb     vm_op_unimpl            ; EE --
                fdb     vm_op_unimpl            ; EF --
                fdb     vm_op_unimpl            ; F0 --
                fdb     vm_op_unimpl            ; F1 --
                fdb     vm_op_unimpl            ; F2 --
                fdb     vm_op_unimpl            ; F3 --
                fdb     vm_op_unimpl            ; F4 --
                fdb     vm_op_unimpl            ; F5 --
                fdb     vm_op_unimpl            ; F6 --
                fdb     vm_op_unimpl            ; F7 --
                fdb     vm_op_unimpl            ; F8 --
                fdb     vm_op_unimpl            ; F9 --
                fdb     vm_op_unimpl            ; FA --
                fdb     vm_op_unimpl            ; FB --
                fdb     vm_op_unimpl            ; FC --
                fdb     vm_op_unimpl            ; FD --
                fdb     vm_op_unimpl            ; FE --
                fdb     vm_op_unimpl            ; FF --

* ── VMTEST_TAB: handler per test opcode ───────────────────────────
VMTEST_TAB:
                fdb     vm_test_unimpl          ; 00 --
                fdb     vm_test_unimpl          ; 01 equaln(vn)
                fdb     vm_test_unimpl          ; 02 equalv(vv)
                fdb     vm_test_unimpl          ; 03 lessn(vn)
                fdb     vm_test_unimpl          ; 04 lessv(vv)
                fdb     vm_test_unimpl          ; 05 greatern(vn)
                fdb     vm_test_unimpl          ; 06 greaterv(vv)
                fdb     vm_test_unimpl          ; 07 isset(n)
                fdb     vm_test_unimpl          ; 08 issetv(v)
                fdb     vm_test_unimpl          ; 09 has(n)
                fdb     vm_test_unimpl          ; 0A obj.in.room(nv)
                fdb     vm_test_unimpl          ; 0B posn(nnnnn)
                fdb     vm_test_unimpl          ; 0C controller(n)
                fdb     vm_test_unimpl          ; 0D have.key()
                fdb     vm_test_unimpl          ; 0E said()
                fdb     vm_test_unimpl          ; 0F compare.strings(ss)
                fdb     vm_test_unimpl          ; 10 obj.in.box(nnnnn)
                fdb     vm_test_unimpl          ; 11 center.posn(nnnnn)
                fdb     vm_test_unimpl          ; 12 right.posn(nnnnn)
                fdb     vm_test_unimpl          ; 13 in.motion.using.mouse()
                fdb     vm_test_unimpl          ; 14 --
                fdb     vm_test_unimpl          ; 15 --
                fdb     vm_test_unimpl          ; 16 --
                fdb     vm_test_unimpl          ; 17 --
                fdb     vm_test_unimpl          ; 18 --
                fdb     vm_test_unimpl          ; 19 --
                fdb     vm_test_unimpl          ; 1A --
                fdb     vm_test_unimpl          ; 1B --
                fdb     vm_test_unimpl          ; 1C --
                fdb     vm_test_unimpl          ; 1D --
                fdb     vm_test_unimpl          ; 1E --
                fdb     vm_test_unimpl          ; 1F --
                fdb     vm_test_unimpl          ; 20 --
                fdb     vm_test_unimpl          ; 21 --
                fdb     vm_test_unimpl          ; 22 --
                fdb     vm_test_unimpl          ; 23 --
                fdb     vm_test_unimpl          ; 24 --
                fdb     vm_test_unimpl          ; 25 --
                fdb     vm_test_unimpl          ; 26 --
                fdb     vm_test_unimpl          ; 27 --
                fdb     vm_test_unimpl          ; 28 --
                fdb     vm_test_unimpl          ; 29 --
                fdb     vm_test_unimpl          ; 2A --
                fdb     vm_test_unimpl          ; 2B --
                fdb     vm_test_unimpl          ; 2C --
                fdb     vm_test_unimpl          ; 2D --
                fdb     vm_test_unimpl          ; 2E --
                fdb     vm_test_unimpl          ; 2F --
                fdb     vm_test_unimpl          ; 30 --
                fdb     vm_test_unimpl          ; 31 --
                fdb     vm_test_unimpl          ; 32 --
                fdb     vm_test_unimpl          ; 33 --
                fdb     vm_test_unimpl          ; 34 --
                fdb     vm_test_unimpl          ; 35 --
                fdb     vm_test_unimpl          ; 36 --
                fdb     vm_test_unimpl          ; 37 --
                fdb     vm_test_unimpl          ; 38 --
                fdb     vm_test_unimpl          ; 39 --
                fdb     vm_test_unimpl          ; 3A --
                fdb     vm_test_unimpl          ; 3B --
                fdb     vm_test_unimpl          ; 3C --
                fdb     vm_test_unimpl          ; 3D --
                fdb     vm_test_unimpl          ; 3E --
                fdb     vm_test_unimpl          ; 3F --
                fdb     vm_test_unimpl          ; 40 --
                fdb     vm_test_unimpl          ; 41 --
                fdb     vm_test_unimpl          ; 42 --
                fdb     vm_test_unimpl          ; 43 --
                fdb     vm_test_unimpl          ; 44 --
                fdb     vm_test_unimpl          ; 45 --
                fdb     vm_test_unimpl          ; 46 --
                fdb     vm_test_unimpl          ; 47 --
                fdb     vm_test_unimpl          ; 48 --
                fdb     vm_test_unimpl          ; 49 --
                fdb     vm_test_unimpl          ; 4A --
                fdb     vm_test_unimpl          ; 4B --
                fdb     vm_test_unimpl          ; 4C --
                fdb     vm_test_unimpl          ; 4D --
                fdb     vm_test_unimpl          ; 4E --
                fdb     vm_test_unimpl          ; 4F --
                fdb     vm_test_unimpl          ; 50 --
                fdb     vm_test_unimpl          ; 51 --
                fdb     vm_test_unimpl          ; 52 --
                fdb     vm_test_unimpl          ; 53 --
                fdb     vm_test_unimpl          ; 54 --
                fdb     vm_test_unimpl          ; 55 --
                fdb     vm_test_unimpl          ; 56 --
                fdb     vm_test_unimpl          ; 57 --
                fdb     vm_test_unimpl          ; 58 --
                fdb     vm_test_unimpl          ; 59 --
                fdb     vm_test_unimpl          ; 5A --
                fdb     vm_test_unimpl          ; 5B --
                fdb     vm_test_unimpl          ; 5C --
                fdb     vm_test_unimpl          ; 5D --
                fdb     vm_test_unimpl          ; 5E --
                fdb     vm_test_unimpl          ; 5F --
                fdb     vm_test_unimpl          ; 60 --
                fdb     vm_test_unimpl          ; 61 --
                fdb     vm_test_unimpl          ; 62 --
                fdb     vm_test_unimpl          ; 63 --
                fdb     vm_test_unimpl          ; 64 --
                fdb     vm_test_unimpl          ; 65 --
                fdb     vm_test_unimpl          ; 66 --
                fdb     vm_test_unimpl          ; 67 --
                fdb     vm_test_unimpl          ; 68 --
                fdb     vm_test_unimpl          ; 69 --
                fdb     vm_test_unimpl          ; 6A --
                fdb     vm_test_unimpl          ; 6B --
                fdb     vm_test_unimpl          ; 6C --
                fdb     vm_test_unimpl          ; 6D --
                fdb     vm_test_unimpl          ; 6E --
                fdb     vm_test_unimpl          ; 6F --
                fdb     vm_test_unimpl          ; 70 --
                fdb     vm_test_unimpl          ; 71 --
                fdb     vm_test_unimpl          ; 72 --
                fdb     vm_test_unimpl          ; 73 --
                fdb     vm_test_unimpl          ; 74 --
                fdb     vm_test_unimpl          ; 75 --
                fdb     vm_test_unimpl          ; 76 --
                fdb     vm_test_unimpl          ; 77 --
                fdb     vm_test_unimpl          ; 78 --
                fdb     vm_test_unimpl          ; 79 --
                fdb     vm_test_unimpl          ; 7A --
                fdb     vm_test_unimpl          ; 7B --
                fdb     vm_test_unimpl          ; 7C --
                fdb     vm_test_unimpl          ; 7D --
                fdb     vm_test_unimpl          ; 7E --
                fdb     vm_test_unimpl          ; 7F --
                fdb     vm_test_unimpl          ; 80 --
                fdb     vm_test_unimpl          ; 81 --
                fdb     vm_test_unimpl          ; 82 --
                fdb     vm_test_unimpl          ; 83 --
                fdb     vm_test_unimpl          ; 84 --
                fdb     vm_test_unimpl          ; 85 --
                fdb     vm_test_unimpl          ; 86 --
                fdb     vm_test_unimpl          ; 87 --
                fdb     vm_test_unimpl          ; 88 --
                fdb     vm_test_unimpl          ; 89 --
                fdb     vm_test_unimpl          ; 8A --
                fdb     vm_test_unimpl          ; 8B --
                fdb     vm_test_unimpl          ; 8C --
                fdb     vm_test_unimpl          ; 8D --
                fdb     vm_test_unimpl          ; 8E --
                fdb     vm_test_unimpl          ; 8F --
                fdb     vm_test_unimpl          ; 90 --
                fdb     vm_test_unimpl          ; 91 --
                fdb     vm_test_unimpl          ; 92 --
                fdb     vm_test_unimpl          ; 93 --
                fdb     vm_test_unimpl          ; 94 --
                fdb     vm_test_unimpl          ; 95 --
                fdb     vm_test_unimpl          ; 96 --
                fdb     vm_test_unimpl          ; 97 --
                fdb     vm_test_unimpl          ; 98 --
                fdb     vm_test_unimpl          ; 99 --
                fdb     vm_test_unimpl          ; 9A --
                fdb     vm_test_unimpl          ; 9B --
                fdb     vm_test_unimpl          ; 9C --
                fdb     vm_test_unimpl          ; 9D --
                fdb     vm_test_unimpl          ; 9E --
                fdb     vm_test_unimpl          ; 9F --
                fdb     vm_test_unimpl          ; A0 --
                fdb     vm_test_unimpl          ; A1 --
                fdb     vm_test_unimpl          ; A2 --
                fdb     vm_test_unimpl          ; A3 --
                fdb     vm_test_unimpl          ; A4 --
                fdb     vm_test_unimpl          ; A5 --
                fdb     vm_test_unimpl          ; A6 --
                fdb     vm_test_unimpl          ; A7 --
                fdb     vm_test_unimpl          ; A8 --
                fdb     vm_test_unimpl          ; A9 --
                fdb     vm_test_unimpl          ; AA --
                fdb     vm_test_unimpl          ; AB --
                fdb     vm_test_unimpl          ; AC --
                fdb     vm_test_unimpl          ; AD --
                fdb     vm_test_unimpl          ; AE --
                fdb     vm_test_unimpl          ; AF --
                fdb     vm_test_unimpl          ; B0 --
                fdb     vm_test_unimpl          ; B1 --
                fdb     vm_test_unimpl          ; B2 --
                fdb     vm_test_unimpl          ; B3 --
                fdb     vm_test_unimpl          ; B4 --
                fdb     vm_test_unimpl          ; B5 --
                fdb     vm_test_unimpl          ; B6 --
                fdb     vm_test_unimpl          ; B7 --
                fdb     vm_test_unimpl          ; B8 --
                fdb     vm_test_unimpl          ; B9 --
                fdb     vm_test_unimpl          ; BA --
                fdb     vm_test_unimpl          ; BB --
                fdb     vm_test_unimpl          ; BC --
                fdb     vm_test_unimpl          ; BD --
                fdb     vm_test_unimpl          ; BE --
                fdb     vm_test_unimpl          ; BF --
                fdb     vm_test_unimpl          ; C0 --
                fdb     vm_test_unimpl          ; C1 --
                fdb     vm_test_unimpl          ; C2 --
                fdb     vm_test_unimpl          ; C3 --
                fdb     vm_test_unimpl          ; C4 --
                fdb     vm_test_unimpl          ; C5 --
                fdb     vm_test_unimpl          ; C6 --
                fdb     vm_test_unimpl          ; C7 --
                fdb     vm_test_unimpl          ; C8 --
                fdb     vm_test_unimpl          ; C9 --
                fdb     vm_test_unimpl          ; CA --
                fdb     vm_test_unimpl          ; CB --
                fdb     vm_test_unimpl          ; CC --
                fdb     vm_test_unimpl          ; CD --
                fdb     vm_test_unimpl          ; CE --
                fdb     vm_test_unimpl          ; CF --
                fdb     vm_test_unimpl          ; D0 --
                fdb     vm_test_unimpl          ; D1 --
                fdb     vm_test_unimpl          ; D2 --
                fdb     vm_test_unimpl          ; D3 --
                fdb     vm_test_unimpl          ; D4 --
                fdb     vm_test_unimpl          ; D5 --
                fdb     vm_test_unimpl          ; D6 --
                fdb     vm_test_unimpl          ; D7 --
                fdb     vm_test_unimpl          ; D8 --
                fdb     vm_test_unimpl          ; D9 --
                fdb     vm_test_unimpl          ; DA --
                fdb     vm_test_unimpl          ; DB --
                fdb     vm_test_unimpl          ; DC --
                fdb     vm_test_unimpl          ; DD --
                fdb     vm_test_unimpl          ; DE --
                fdb     vm_test_unimpl          ; DF --
                fdb     vm_test_unimpl          ; E0 --
                fdb     vm_test_unimpl          ; E1 --
                fdb     vm_test_unimpl          ; E2 --
                fdb     vm_test_unimpl          ; E3 --
                fdb     vm_test_unimpl          ; E4 --
                fdb     vm_test_unimpl          ; E5 --
                fdb     vm_test_unimpl          ; E6 --
                fdb     vm_test_unimpl          ; E7 --
                fdb     vm_test_unimpl          ; E8 --
                fdb     vm_test_unimpl          ; E9 --
                fdb     vm_test_unimpl          ; EA --
                fdb     vm_test_unimpl          ; EB --
                fdb     vm_test_unimpl          ; EC --
                fdb     vm_test_unimpl          ; ED --
                fdb     vm_test_unimpl          ; EE --
                fdb     vm_test_unimpl          ; EF --
                fdb     vm_test_unimpl          ; F0 --
                fdb     vm_test_unimpl          ; F1 --
                fdb     vm_test_unimpl          ; F2 --
                fdb     vm_test_unimpl          ; F3 --
                fdb     vm_test_unimpl          ; F4 --
                fdb     vm_test_unimpl          ; F5 --
                fdb     vm_test_unimpl          ; F6 --
                fdb     vm_test_unimpl          ; F7 --
                fdb     vm_test_unimpl          ; F8 --
                fdb     vm_test_unimpl          ; F9 --
                fdb     vm_test_unimpl          ; FA --
                fdb     vm_test_unimpl          ; FB --
                fdb     vm_test_unimpl          ; FC --
                fdb     vm_test_unimpl          ; FD --
                fdb     vm_test_unimpl          ; FE --
                fdb     vm_test_unimpl          ; FF --
