"""AGI opcode base tables -- GENERATED, DO NOT EDIT BY HAND.

Generated by harness/tools/gen_opcode_table.py from the pinned oracle:
    commit 9d9b9e93108a276c551aeffa390169ccc5148e15
    engines/agi/opcodes.cpp + agi.h

Regenerate:  python harness/tools/gen_opcode_table.py
Verify:      python harness/tools/gen_opcode_table.py --check

Each entry is (name, parameters, handler). `parameters` is ScummVM's own type string;
its LENGTH is the instruction's parameter byte count -- opcodes.cpp computes
parameterSize as strlen(parameters), so every parameter is exactly one byte. The type
letters are: n = literal number, v = variable number, s = message/string number.

★ TWO ENTRIES CARRY NO HANDLER AND ARE NOT DEFECTS:
  commands[0x00] 'return'  -- handled inline by the interpreter loop, never dispatched
  tests[0x00]    ''        -- condUnknown; an illegal test opcode

★ 'said' (test 0x0E) has an EMPTY parameter string and is NOT zero-length. Its operand
count is read from the instruction stream: a leading byte N, then N 16-bit words.
op_test.cpp skipInstruction() special-cases it. A table-driven skip that trusts the
empty string here desynchronises the whole instruction stream.
"""

# opCodesV1Cond -- 17 entries (opcodes 0x00-0x10)
V1_TESTS = [
    ("",                      "",        "condUnknown"),             # 00
    ("equaln",                "vn",      "condEqual"),               # 01
    ("equalv",                "vv",      "condEqualV"),              # 02
    ("lessn",                 "vn",      "condLess"),                # 03
    ("lessv",                 "vv",      "condLessV"),               # 04
    ("greatern",              "vn",      "condGreater"),             # 05
    ("greaterv",              "vv",      "condGreaterV"),            # 06
    ("isset",                 "v",       "condIsSetV1"),             # 07
    ("has",                   "n",       "condHasV1"),               # 08
    ("said",                  "nnnn",    "condSaid2"),               # 09
    ("posn",                  "nnnnn",   "condPosn"),                # 0A
    ("controller",            "n",       "condController"),          # 0B
    ("obj.in.room",           "nv",      "condObjInRoom"),           # 0C
    ("said",                  "nnnnnn",  "condSaid3"),               # 0D
    ("have.key",              "",        "condHaveKey"),             # 0E
    ("said",                  "nn",      "condSaid1"),               # 0F
    ("bit",                   "nv",      "condBit"),                 # 10
]

# opCodesV1 -- 99 entries (opcodes 0x00-0x62)
V1_COMMANDS = [
    ("return",                "",        None),                      # 00
    ("increment",             "v",       "cmdIncrement"),            # 01
    ("decrement",             "v",       "cmdDecrement"),            # 02
    ("assignn",               "vn",      "cmdAssignN"),              # 03
    ("assignv",               "vv",      "cmdAssignV"),              # 04
    ("addn",                  "vn",      "cmdAddN"),                 # 05
    ("addv",                  "vv",      "cmdAddV"),                 # 06
    ("subn",                  "vn",      "cmdSubN"),                 # 07
    ("subv",                  "vv",      "cmdSubV"),                 # 08
    ("load.view",             "n",       "cmdLoadView"),             # 09
    ("animate.obj",           "n",       "cmdAnimateObj"),           # 0A
    ("new.room",              "n",       "cmdNewRoom"),              # 0B
    ("draw.pic",              "v",       "cmdDrawPicV1"),            # 0C
    ("print",                 "s",       "cmdPrint"),                # 0D
    ("status",                "",        "cmdStatus"),               # 0E
    ("save.game",             "",        "cmdSaveGame"),             # 0F
    ("restore.game",          "",        "cmdLoadGame"),             # 10
    ("init.disk",             "",        "cmdInitDisk"),             # 11
    ("restart.game",          "",        "cmdRestartGame"),          # 12
    ("random",                "v",       "cmdRandomV1"),             # 13
    ("get",                   "n",       "cmdGetV1"),                # 14
    ("drop",                  "n",       "cmdDrop"),                 # 15
    ("draw",                  "n",       "cmdDraw"),                 # 16
    ("erase",                 "n",       "cmdErase"),                # 17
    ("position",              "nnn",     "cmdPositionV1"),           # 18
    ("position.v",            "nvv",     "cmdPositionFV1"),          # 19
    ("get.posn",              "nvv",     "cmdGetPosn"),              # 1A
    ("set.cel",               "nn",      "cmdSetCel"),               # 1B
    ("set.loop",              "nn",      "cmdSetLoop"),              # 1C
    ("end.of.loop",           "nn",      "cmdEndOfLoopV1"),          # 1D
    ("reverse.loop",          "nn",      "cmdReverseLoopV1"),        # 1E
    ("move.obj",              "nnnnn",   "cmdMoveObj"),              # 1F
    ("set.view",              "nn",      "cmdSetView"),              # 20
    ("follow.ego",            "nnv",     "cmdFollowEgo"),            # 21
    ("block",                 "nnnn",    "cmdBlock"),                # 22
    ("unblock",               "",        "cmdUnblock"),              # 23
    ("ignore.blocks",         "n",       "cmdIgnoreBlocks"),         # 24
    ("observe.blocks",        "n",       "cmdObserveBlocks"),        # 25
    ("wander",                "n",       "cmdWander"),               # 26
    ("reposition",            "nvv",     "cmdRepositionV1"),         # 27
    ("stop.motion",           "n",       "cmdStopMotionV1"),         # 28
    ("start.motion",          "n",       "cmdStartMotionV1"),        # 29
    ("stop.cycling",          "n",       "cmdStopCycling"),          # 2A
    ("start.cycling",         "n",       "cmdStartCycling"),         # 2B
    ("stop.update",           "n",       "cmdStopUpdate"),           # 2C
    ("start.update",          "n",       "cmdStartUpdate"),          # 2D
    ("program.control",       "",        "cmdProgramControl"),       # 2E
    ("player.control",        "",        "cmdPlayerControl"),        # 2F
    ("set.priority",          "nn",      "cmdSetPriority"),          # 30
    ("release.priority",      "n",       "cmdReleasePriority"),      # 31
    ("add.to.pic",            "nnnnnn",  "cmdAddToPicV1"),           # 32
    ("set.horizon",           "n",       "cmdSetHorizon"),           # 33
    ("ignore.horizon",        "n",       "cmdIgnoreHorizon"),        # 34
    ("observe.horizon",       "n",       "cmdObserveHorizon"),       # 35
    ("load.logics",           "n",       "cmdLoadLogic"),            # 36
    ("object.on.water",       "n",       "cmdObjectOnWater"),        # 37
    ("load.pic",              "v",       "cmdLoadPicV1"),            # 38
    ("load.sound",            "n",       "cmdLoadSound"),            # 39
    ("sound",                 "nn",      "cmdSound"),                # 3A
    ("stop.sound",            "",        "cmdStopSound"),            # 3B
    ("set.v",                 "v",       "cmdSetV"),                 # 3C
    ("reset.v",               "v",       "cmdResetV"),               # 3D
    ("toggle.v",              "v",       "cmdToggleV"),              # 3E
    ("new.room.v",            "v",       "cmdNewRoom"),              # 3F
    ("call",                  "n",       "cmdCallV1"),               # 40
    ("quit",                  "",        "cmdQuitV1"),               # 41
    ("set.speed",             "v",       "cmdSetSpeed"),             # 42
    ("move.obj.v",            "nvvvv",   "cmdMoveObjF"),             # 43
    ("get.num",               "nv",      "cmdUnknown"),              # 44
    ("get.v",                 "v",       "cmdUnknown"),              # 45
    ("assign.v",              "vv",      "cmdUnknown"),              # 46
    ("printvar",              "v",       "cmdUnknown"),              # 47
    ("get.priority",          "nv",      "cmdGetPriority"),          # 48
    ("ignore.objs",           "n",       "cmdIgnoreObjs"),           # 49
    ("observe.objs",          "n",       "cmdObserveObjs"),          # 4A
    ("distance",              "nnv",     "cmdDistance"),             # 4B
    ("object.on.land",        "n",       "cmdObjectOnLand"),         # 4C
    ("set.priority.v",        "nv",      "cmdUnknown"),              # 4D
    ("show.obj",              "n",       "cmdShowObj"),              # 4E
    ("load.logics",           "n",       "cmdLoadLogic"),            # 4F
    ("display",               "nnns",    "cmdDisplay"),              # 50
    ("prevent.input",         "",        "cmdUnknown"),              # 51
    ("...",                   "",        "cmdUnknown"),              # 52
    ("text.screen",           "n",       "cmdUnknown"),              # 53
    ("graphics",              "",        "cmdUnknown"),              # 54
    ("stop.motion",           "",        "cmdStopMotion"),           # 55
    ("discard.view",          "n",       "cmdDiscardView"),          # 56
    ("discard.pic",           "v",       "cmdDiscardPic"),           # 57
    ("set.item.view",         "nn",      "cmdSetItemView"),          # 58
    ("reverse.cycle",         "n",       "cmdReverseCycle"),         # 59
    ("last.cel",              "nv",      "cmdLastCel"),              # 5A
    ("set.cel.v",             "nv",      "cmdSetCelF"),              # 5B
    ("normal.cycle",          "n",       "cmdNormalCycle"),          # 5C
    ("load.view",             "n",       "cmdLoadView"),             # 5D
    ("...",                   "n",       "cmdUnknown"),              # 5E
    ("...",                   "",        "cmdUnknown"),              # 5F
    ("set.bit",               "nv",      "cmdSetBit"),               # 60
    ("clear.bit",             "nv",      "cmdClearBit"),             # 61
    ("set.upper.left",        "nn",      "cmdSetUpperLeft"),         # 62
]

# opCodesV2Cond -- 20 entries (opcodes 0x00-0x13)
V2_TESTS = [
    ("",                      "",        "condUnknown"),             # 00
    ("equaln",                "vn",      "condEqual"),               # 01
    ("equalv",                "vv",      "condEqualV"),              # 02
    ("lessn",                 "vn",      "condLess"),                # 03
    ("lessv",                 "vv",      "condLessV"),               # 04
    ("greatern",              "vn",      "condGreater"),             # 05
    ("greaterv",              "vv",      "condGreaterV"),            # 06
    ("isset",                 "n",       "condIsSet"),               # 07
    ("issetv",                "v",       "condIsSetV"),              # 08
    ("has",                   "n",       "condHas"),                 # 09
    ("obj.in.room",           "nv",      "condObjInRoom"),           # 0A
    ("posn",                  "nnnnn",   "condPosn"),                # 0B
    ("controller",            "n",       "condController"),          # 0C
    ("have.key",              "",        "condHaveKey"),             # 0D
    ("said",                  "",        "condSaid"),                # 0E
    ("compare.strings",       "ss",      "condCompareStrings"),      # 0F
    ("obj.in.box",            "nnnnn",   "condObjInBox"),            # 10
    ("center.posn",           "nnnnn",   "condCenterPosn"),          # 11
    ("right.posn",            "nnnnn",   "condRightPosn"),           # 12
    ("in.motion.using.mouse", "",        "condUnknown13"),           # 13
]

# opCodesV2 -- 183 entries (opcodes 0x00-0xB6)
V2_COMMANDS = [
    ("return",                "",        None),                      # 00
    ("increment",             "v",       "cmdIncrement"),            # 01
    ("decrement",             "v",       "cmdDecrement"),            # 02
    ("assignn",               "vn",      "cmdAssignN"),              # 03
    ("assignv",               "vv",      "cmdAssignV"),              # 04
    ("addn",                  "vn",      "cmdAddN"),                 # 05
    ("addv",                  "vv",      "cmdAddV"),                 # 06
    ("subn",                  "vn",      "cmdSubN"),                 # 07
    ("subv",                  "vv",      "cmdSubV"),                 # 08
    ("lindirectv",            "vv",      "cmdLindirectV"),           # 09
    ("lindirect",             "vv",      "cmdRindirect"),            # 0A
    ("lindirectn",            "vn",      "cmdLindirectN"),           # 0B
    ("set",                   "n",       "cmdSet"),                  # 0C
    ("reset",                 "n",       "cmdReset"),                # 0D
    ("toggle",                "n",       "cmdToggle"),               # 0E
    ("set.v",                 "v",       "cmdSetV"),                 # 0F
    ("reset.v",               "v",       "cmdResetV"),               # 10
    ("toggle.v",              "v",       "cmdToggleV"),              # 11
    ("new.room",              "n",       "cmdNewRoom"),              # 12
    ("new.room.v",            "v",       "cmdNewRoomF"),             # 13
    ("load.logics",           "n",       "cmdLoadLogic"),            # 14
    ("load.logics.v",         "v",       "cmdLoadLogicF"),           # 15
    ("call",                  "n",       "cmdCall"),                 # 16
    ("call.v",                "v",       "cmdCallF"),                # 17
    ("load.pic",              "v",       "cmdLoadPic"),              # 18
    ("draw.pic",              "v",       "cmdDrawPic"),              # 19
    ("show.pic",              "",        "cmdShowPic"),              # 1A
    ("discard.pic",           "v",       "cmdDiscardPic"),           # 1B
    ("overlay.pic",           "v",       "cmdOverlayPic"),           # 1C
    ("show.pri.screen",       "",        "cmdShowPriScreen"),        # 1D
    ("load.view",             "n",       "cmdLoadView"),             # 1E
    ("load.view.v",           "v",       "cmdLoadViewF"),            # 1F
    ("discard.view",          "n",       "cmdDiscardView"),          # 20
    ("animate.obj",           "n",       "cmdAnimateObj"),           # 21
    ("unanimate.all",         "",        "cmdUnanimateAll"),         # 22
    ("draw",                  "n",       "cmdDraw"),                 # 23
    ("erase",                 "n",       "cmdErase"),                # 24
    ("position",              "nnn",     "cmdPosition"),             # 25
    ("position.v",            "nvv",     "cmdPositionF"),            # 26
    ("get.posn",              "nvv",     "cmdGetPosn"),              # 27
    ("reposition",            "nvv",     "cmdReposition"),           # 28
    ("set.view",              "nn",      "cmdSetView"),              # 29
    ("set.view.v",            "nv",      "cmdSetViewF"),             # 2A
    ("set.loop",              "nn",      "cmdSetLoop"),              # 2B
    ("set.loop.v",            "nv",      "cmdSetLoopF"),             # 2C
    ("fix.loop",              "n",       "cmdFixLoop"),              # 2D
    ("release.loop",          "n",       "cmdReleaseLoop"),          # 2E
    ("set.cel",               "nn",      "cmdSetCel"),               # 2F
    ("set.cel.v",             "nv",      "cmdSetCelF"),              # 30
    ("last.cel",              "nv",      "cmdLastCel"),              # 31
    ("current.cel",           "nv",      "cmdCurrentCel"),           # 32
    ("current.loop",          "nv",      "cmdCurrentLoop"),          # 33
    ("current.view",          "nv",      "cmdCurrentView"),          # 34
    ("number.of.loops",       "nv",      "cmdNumberOfLoops"),        # 35
    ("set.priority",          "nn",      "cmdSetPriority"),          # 36
    ("set.priority.v",        "nv",      "cmdSetPriorityF"),         # 37
    ("release.priority",      "n",       "cmdReleasePriority"),      # 38
    ("get.priority",          "nn",      "cmdGetPriority"),          # 39
    ("stop.update",           "n",       "cmdStopUpdate"),           # 3A
    ("start.update",          "n",       "cmdStartUpdate"),          # 3B
    ("force.update",          "n",       "cmdForceUpdate"),          # 3C
    ("ignore.horizon",        "n",       "cmdIgnoreHorizon"),        # 3D
    ("observe.horizon",       "n",       "cmdObserveHorizon"),       # 3E
    ("set.horizon",           "n",       "cmdSetHorizon"),           # 3F
    ("object.on.water",       "n",       "cmdObjectOnWater"),        # 40
    ("object.on.land",        "n",       "cmdObjectOnLand"),         # 41
    ("object.on.anything",    "n",       "cmdObjectOnAnything"),     # 42
    ("ignore.objs",           "n",       "cmdIgnoreObjs"),           # 43
    ("observe.objs",          "n",       "cmdObserveObjs"),          # 44
    ("distance",              "nnv",     "cmdDistance"),             # 45
    ("stop.cycling",          "n",       "cmdStopCycling"),          # 46
    ("start.cycling",         "n",       "cmdStartCycling"),         # 47
    ("normal.cycle",          "n",       "cmdNormalCycle"),          # 48
    ("end.of.loop",           "nn",      "cmdEndOfLoop"),            # 49
    ("reverse.cycle",         "n",       "cmdReverseCycle"),         # 4A
    ("reverse.loop",          "nn",      "cmdReverseLoop"),          # 4B
    ("cycle.time",            "nv",      "cmdCycleTime"),            # 4C
    ("stop.motion",           "n",       "cmdStopMotion"),           # 4D
    ("start.motion",          "n",       "cmdStartMotion"),          # 4E
    ("step.size",             "nv",      "cmdStepSize"),             # 4F
    ("step.time",             "nv",      "cmdStepTime"),             # 50
    ("move.obj",              "nnnnn",   "cmdMoveObj"),              # 51
    ("move.obj.v",            "nvvvv",   "cmdMoveObjF"),             # 52
    ("follow.ego",            "nnn",     "cmdFollowEgo"),            # 53
    ("wander",                "n",       "cmdWander"),               # 54
    ("normal.motion",         "n",       "cmdNormalMotion"),         # 55
    ("set.dir",               "nv",      "cmdSetDir"),               # 56
    ("get.dir",               "nv",      "cmdGetDir"),               # 57
    ("ignore.blocks",         "n",       "cmdIgnoreBlocks"),         # 58
    ("observe.blocks",        "n",       "cmdObserveBlocks"),        # 59
    ("block",                 "nnnn",    "cmdBlock"),                # 5A
    ("unblock",               "",        "cmdUnblock"),              # 5B
    ("get",                   "n",       "cmdGet"),                  # 5C
    ("get.v",                 "v",       "cmdGetF"),                 # 5D
    ("drop",                  "n",       "cmdDrop"),                 # 5E
    ("put",                   "nn",      "cmdPut"),                  # 5F
    ("put.v",                 "vv",      "cmdPutF"),                 # 60
    ("get.room.v",            "vv",      "cmdGetRoomF"),             # 61
    ("load.sound",            "n",       "cmdLoadSound"),            # 62
    ("sound",                 "nn",      "cmdSound"),                # 63
    ("stop.sound",            "",        "cmdStopSound"),            # 64
    ("print",                 "s",       "cmdPrint"),                # 65
    ("print.v",               "v",       "cmdPrintF"),               # 66
    ("display",               "nns",     "cmdDisplay"),              # 67
    ("display.v",             "vvv",     "cmdDisplayF"),             # 68
    ("clear.lines",           "nns",     "cmdClearLines"),           # 69
    ("text.screen",           "",        "cmdTextScreen"),           # 6A
    ("graphics",              "",        "cmdGraphics"),             # 6B
    ("set.cursor.char",       "s",       "cmdSetCursorChar"),        # 6C
    ("set.text.attribute",    "nn",      "cmdSetTextAttribute"),     # 6D
    ("shake.screen",          "n",       "cmdShakeScreen"),          # 6E
    ("configure.screen",      "nnn",     "cmdConfigureScreen"),      # 6F
    ("status.line.on",        "",        "cmdStatusLineOn"),         # 70
    ("status.line.off",       "",        "cmdStatusLineOff"),        # 71
    ("set.string",            "ns",      "cmdSetString"),            # 72
    ("get.string",            "nsnnn",   "cmdGetString"),            # 73
    ("word.to.string",        "nn",      "cmdWordToString"),         # 74
    ("parse",                 "n",       "cmdParse"),                # 75
    ("get.num",               "nv",      "cmdGetNum"),               # 76
    ("prevent.input",         "",        "cmdPreventInput"),         # 77
    ("accept.input",          "",        "cmdAcceptInput"),          # 78
    ("set.key",               "nnn",     "cmdSetKey"),               # 79
    ("add.to.pic",            "nnnnnnn", "cmdAddToPic"),             # 7A
    ("add.to.pic.v",          "vvvvvvv", "cmdAddToPicF"),            # 7B
    ("status",                "",        "cmdStatus"),               # 7C
    ("save.game",             "",        "cmdSaveGame"),             # 7D
    ("restore.game",          "",        "cmdLoadGame"),             # 7E
    ("init.disk",             "",        "cmdInitDisk"),             # 7F
    ("restart.game",          "",        "cmdRestartGame"),          # 80
    ("show.obj",              "n",       "cmdShowObj"),              # 81
    ("random",                "nnv",     "cmdRandom"),               # 82
    ("program.control",       "",        "cmdProgramControl"),       # 83
    ("player.control",        "",        "cmdPlayerControl"),        # 84
    ("obj.status.v",          "v",       "cmdObjStatusF"),           # 85
    ("quit",                  "n",       "cmdQuit"),                 # 86
    ("show.mem",              "",        "cmdShowMem"),              # 87
    ("pause",                 "",        "cmdPause"),                # 88
    ("echo.line",             "",        "cmdEchoLine"),             # 89
    ("cancel.line",           "",        "cmdCancelLine"),           # 8A
    ("init.joy",              "",        "cmdInitJoy"),              # 8B
    ("toggle.monitor",        "",        "cmdToggleMonitor"),        # 8C
    ("version",               "",        "cmdVersion"),              # 8D
    ("script.size",           "n",       "cmdScriptSize"),           # 8E
    ("set.game.id",           "s",       "cmdSetGameID"),            # 8F
    ("log",                   "s",       "cmdLog"),                  # 90
    ("set.scan.start",        "",        "cmdSetScanStart"),         # 91
    ("reset.scan.start",      "",        "cmdResetScanStart"),       # 92
    ("reposition.to",         "nnn",     "cmdRepositionTo"),         # 93
    ("reposition.to.v",       "nvv",     "cmdRepositionToF"),        # 94
    ("trace.on",              "",        "cmdTraceOn"),              # 95
    ("trace.info",            "nnn",     "cmdTraceInfo"),            # 96
    ("print.at",              "snnn",    "cmdPrintAt"),              # 97
    ("print.at.v",            "vnnn",    "cmdPrintAtV"),             # 98
    ("discard.view.v",        "v",       "cmdDiscardView"),          # 99
    ("clear.text.rect",       "nnnnn",   "cmdClearTextRect"),        # 9A
    ("set.upper.left",        "nn",      "cmdSetUpperLeft"),         # 9B
    ("set.menu",              "s",       "cmdSetMenu"),              # 9C
    ("set.menu.item",         "sn",      "cmdSetMenuItem"),          # 9D
    ("submit.menu",           "",        "cmdSubmitMenu"),           # 9E
    ("enable.item",           "n",       "cmdEnableItem"),           # 9F
    ("disable.item",          "n",       "cmdDisableItem"),          # A0
    ("menu.input",            "",        "cmdMenuInput"),            # A1
    ("show.obj.v",            "v",       "cmdShowObjV"),             # A2
    ("open.dialogue",         "",        "cmdOpenDialogue"),         # A3
    ("close.dialogue",        "",        "cmdCloseDialogue"),        # A4
    ("mul.n",                 "vn",      "cmdMulN"),                 # A5
    ("mul.v",                 "vv",      "cmdMulV"),                 # A6
    ("div.n",                 "vn",      "cmdDivN"),                 # A7
    ("div.v",                 "vv",      "cmdDivV"),                 # A8
    ("close.window",          "",        "cmdCloseWindow"),          # A9
    ("set.simple",            "n",       "cmdSetSimple"),            # AA
    ("push.script",           "",        "cmdPushScript"),           # AB
    ("pop.script",            "",        "cmdPopScript"),            # AC
    ("hold.key",              "",        "cmdHoldKey"),              # AD
    ("set.pri.base",          "n",       "cmdSetPriBase"),           # AE
    ("discard.sound",         "n",       "cmdDiscardSound"),         # AF
    ("hide.mouse",            "",        "cmdHideMouse"),            # B0
    ("allow.menu",            "n",       "cmdAllowMenu"),            # B1
    ("show.mouse",            "",        "cmdShowMouse"),            # B2
    ("fence.mouse",           "nnnn",    "cmdFenceMouse"),           # B3
    ("get.mse.posn",          "vv",      "cmdGetMousePosn"),         # B4
    ("release.key",           "",        "cmdReleaseKey"),           # B5
    ("adj.ego.move.to.x.y",   "",        "cmdAdjEgoMoveToXY"),       # B6
]

SAID_TEST_OPCODE = 0x0E  # variable length; see module docstring

# ComputerType_* -- 5 members, from engines/agi/agi.h
kAgiComputerPC                     = 0
kAgiComputerApple2                 = 3
kAgiComputerAtariST                = 4
kAgiComputerAmiga                  = 5
kAgiComputerApple2GS               = 7

# CycleMode_* -- 4 members, from engines/agi/agi.h
kCycleNormal                       = 0
kCycleEndOfLoop                    = 1
kCycleRevLoop                      = 2
kCycleReverse                      = 3

# MonitorType_* -- 3 members, from engines/agi/agi.h
kAgiMonitorCga                     = 0
kAgiMonitorHercules                = 2
kAgiMonitorEga                     = 3

# MotionType_* -- 5 members, from engines/agi/agi.h
kMotionNormal                      = 0
kMotionWander                      = 1
kMotionFollowEgo                   = 2
kMotionMoveObj                     = 3
kMotionEgo                         = 4

# SoundType_* -- 3 members, from engines/agi/agi.h
kAgiSoundPC                        = 1
kAgiSoundTandy                     = 3
kAgiSound2GSOld                    = 8

# VM_FLAG_* -- 17 members, from engines/agi/agi.h
VM_FLAG_EGO_WATER                  = 0
VM_FLAG_EGO_INVISIBLE              = 1
VM_FLAG_ENTERED_CLI                = 2
VM_FLAG_EGO_TOUCHED_P2             = 3
VM_FLAG_SAID_ACCEPTED_INPUT        = 4
VM_FLAG_NEW_ROOM_EXEC              = 5
VM_FLAG_RESTART_GAME               = 6
VM_FLAG_SCRIPT_BLOCKED             = 7
VM_FLAG_JOY_SENSITIVITY            = 8
VM_FLAG_SOUND_ON                   = 9
VM_FLAG_DEBUGGER_ON                = 10
VM_FLAG_LOGIC_ZERO_FIRST_TIME      = 11
VM_FLAG_RESTORE_JUST_RAN           = 12
VM_FLAG_STATUS_SELECTS_ITEMS       = 13
VM_FLAG_MENUS_ACCESSIBLE           = 14
VM_FLAG_OUTPUT_MODE                = 15
VM_FLAG_AUTO_RESTART               = 16

# VM_VAR_* -- 30 members, from engines/agi/agi.h
VM_VAR_CURRENT_ROOM                = 0
VM_VAR_PREVIOUS_ROOM               = 1
VM_VAR_BORDER_TOUCH_EGO            = 2
VM_VAR_SCORE                       = 3
VM_VAR_BORDER_CODE                 = 4
VM_VAR_BORDER_TOUCH_OBJECT         = 5
VM_VAR_EGO_DIRECTION               = 6
VM_VAR_MAX_SCORE                   = 7
VM_VAR_FREE_PAGES                  = 8
VM_VAR_WORD_NOT_FOUND              = 9
VM_VAR_TIME_DELAY                  = 10
VM_VAR_SECONDS                     = 11
VM_VAR_MINUTES                     = 12
VM_VAR_HOURS                       = 13
VM_VAR_DAYS                        = 14
VM_VAR_JOYSTICK_SENSITIVITY        = 15
VM_VAR_EGO_VIEW_RESOURCE           = 16
VM_VAR_AGI_ERROR_CODE              = 17
VM_VAR_AGI_ERROR_INFO              = 18
VM_VAR_KEY                         = 19
VM_VAR_COMPUTER                    = 20
VM_VAR_WINDOW_AUTO_CLOSE_TIMER     = 21
VM_VAR_SOUNDGENERATOR              = 22
VM_VAR_VOLUME                      = 23
VM_VAR_MAX_INPUT_CHARACTERS        = 24
VM_VAR_SELECTED_INVENTORY_ITEM     = 25
VM_VAR_MONITOR                     = 26
VM_VAR_MOUSE_BUTTONSTATE           = 27
VM_VAR_MOUSE_X                     = 28
VM_VAR_MOUSE_Y                     = 29

# ViewFlag_* -- 16 members, from engines/agi/agi.h
fDrawn                             = 1
fIgnoreBlocks                      = 2
fFixedPriority                     = 4
fIgnoreHorizon                     = 8
fUpdate                            = 16
fCycling                           = 32
fAnimated                          = 64
fMotion                            = 128
fOnWater                           = 256
fIgnoreObjects                     = 512
fUpdatePos                         = 1024
fOnLand                            = 2048
fDontUpdate                        = 4096
fFixLoop                           = 8192
fDidntMove                         = 16384
fAdjEgoXY                          = 32768
