#!/usr/bin/env python3
"""harness/tools/gen_vm_tables.py -- generate the 6809 VM's dispatch tables from optable.py.

★★★ AC-4, and L-29 is why this exists rather than a hand-typed table. `optable.py` is itself
GENERATED from the pinned oracle by gen_oracle_tables.py, and state.py records what happened
when its constants were typed by hand instead: "the first draft typed them from memory and got
four VM_VAR/VM_FLAG names or values wrong and the ENTIRE ViewFlags bit assignment wrong". None
of those errors raise -- they silently address the wrong variable.

★★ SO THE CHAIN IS: pinned oracle -> gen_oracle_tables.py -> optable.py -> THIS -> the 6809
include. Every link is generated and every link has a --check. Nothing in it is typed twice.

★ WHAT IS EMITTED, and why each piece:
    VMOP_ARGS   256 bytes  argument count per command opcode. The interpreter advances `ip` by
                           this after each handler; a wrong entry desynchronises the stream and
                           every subsequent opcode is garbage.
    VMOP_TAB    512 bytes  handler address per command opcode (16-bit, big-endian).
    VMTEST_TAB  512 bytes  handler address per test opcode.
    ★★ Unimplemented entries point at vm_op_unimpl, NOT at an rts. A silent no-op is forbidden
    by AC-5: it desynchronises nothing and diverges everything, so the diff would report a
    symptom hundreds of cycles after the cause.

★ Handler labels are derived mechanically from the oracle's own handler names, so a handler
that exists in the assembly but is spelled differently from the oracle is a MISSING handler
here rather than a silent mismatch.
"""
import argparse
import io
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

from agivm import optable  # noqa: E402

HEADER = """* src/harness/vm_tables.s -- GENERATED by harness/tools/gen_vm_tables.py. DO NOT EDIT.
*
* ★★★ Generated from tools/agivm/optable.py, which is itself generated from the pinned oracle
* by gen_oracle_tables.py. Editing this file by hand breaks that chain, and the chain is the
* only reason the constants are trusted: state.py records four wrong VM_VAR/VM_FLAG values and
* an entirely reversed ViewFlags assignment from the one time they were typed by hand.
*
* ★ Regenerate:  python harness/tools/gen_vm_tables.py --out src/harness/vm_tables.s
* ★ Drift check: python harness/tools/gen_vm_tables.py --check
*
* source: V2_TESTS {ntests} entries, V2_COMMANDS {ncmds} entries
"""


def label_for(handler_name):
    """cmdAssignN -> assign_n ; condEqual -> equal. Mechanical, never invented.

    ★ Returns None for a table entry the oracle itself leaves unbound -- those are opcodes that
    exist in the table with no handler at all, and they must reach vm_op_unimpl like any other
    unimplemented one rather than being silently skipped here.
    """
    if not handler_name:
        return None
    s = re.sub(r"^(cmd|cond)", "", handler_name)
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()
    return s


def statuses():
    """opcode -> implemented / modelled / unimplemented, taken from the REFERENCE.

    ★★★ AC-5 forbids a silent no-op for an UNIMPLEMENTED opcode. It does not forbid a declared
    no-op for a MODELLED one -- an opcode whose only effects are presentation and which changes
    nothing the state diff can observe. The reference already draws that line and has measured
    it; taking the classification from there rather than re-deciding it here means the two VMs
    cannot disagree about which opcodes are allowed to do nothing.
    """
    from agivm.cycle import Vm
    from volread import resource
    import os
    g = os.environ.get("VM_STATUS_GAME", "C:/Projects/agi-games/pc/Kingquest1")
    vm = Vm(resource.load_from_files(g), 0x2917, platform="dos", game_id="", seed=1)
    out = {}
    for kind, tbl in (("cmd", vm.table.commands), ("test", vm.table.tests)):
        for i, op in enumerate(tbl):
            if op is not None:
                out[(kind, i)] = op.status
    return out


def build(implemented, status):
    """-> the assembly text. `implemented` is the set of labels the assembly actually defines."""
    cmds = optable.V2_COMMANDS
    tests = optable.V2_TESTS
    out = [HEADER.format(ntests=len(tests), ncmds=len(cmds))]

    # ── constants ──────────────────────────────────────────────────────────────────────
    # ★★★ ADDED AT P4.4, AFTER TYPING THEM BY HAND COST A GATE. The first VM assembly declared
    # VAR_*/FLAG_*/kAgi* and the ViewFlag bits by hand and got TWO wrong:
    # VM_VAR_MAX_INPUT_CHARACTERS as 53 (it is 24) and kAgiSoundPC as 0 (it is 1). Neither
    # raises; they write the wrong variable and the state diff reports it three cycles later as
    # "var 24 oracle=38 guest=0; var 53 oracle=0 guest=38".
    # ★★ state.py records the SAME failure one layer up -- "the first draft typed them from
    # memory and got four VM_VAR/VM_FLAG names or values wrong and the ENTIRE ViewFlags bit
    # assignment wrong". That is L-29 twice in one project, so the constants are generated now.
    out.append("\n* ── constants, generated from optable.py ──────────────────────────")
    out.append("* ★ Do not hand-edit and do not duplicate these in a .s file. Two were wrong when")
    out.append("* they were typed, and a wrong variable NUMBER is invisible until the diff runs.")
    names = [n for n in dir(optable)
             if n.startswith(("VM_VAR_", "VM_FLAG_", "kAgi", "kCycle", "kMotion", "f"))
             and isinstance(getattr(optable, n), int)]
    for n in sorted(names):
        v = getattr(optable, n)
        # ViewFlags are 16-bit masks; everything else is a small number
        if n.startswith("f") and v > 255:
            out.append("%-23s equ     $%04X" % (n, v))
        elif n.startswith("f"):
            out.append("%-23s equ     $%04X" % (n, v))
        else:
            out.append("%-23s equ     %d" % (n, v))

    for tabname in ("DIR_TABLE", "DIR_DX", "DIR_DY", "LOOP_TABLE_2", "LOOP_TABLE_4"):
        vals = getattr(optable, tabname, None)
        if vals is None:
            continue
        out.append("VMT_%-19s fcb     %s"
                   % (tabname, ",".join("$%02X" % (v & 0xFF) for v in vals)))

    # ── argument counts ────────────────────────────────────────────────────────────────
    out.append("\n* ── VMOP_ARGS: argument bytes per command opcode ──────────────────")
    out.append("* ★ ScummVM: parameterSize = strlen(parameters). Every parameter is one byte.")
    out.append("VMOP_ARGS:")
    args = [0] * 256
    # ★★★ THE INDEX *IS* THE OPCODE. dispatch.py: `self.commands[i] = Opcode(i, ...)`.
    # ★ The first draft of this generator used args[i+1] and cmds[i-1], which would have wired
    # EVERY handler to the wrong opcode and every argument count one place off -- silently, and
    # the diff would have diverged at cycle 1 pointing at a symptom. Generating a table does not
    # protect against a wrong index base; only checking it against the authority does, which is
    # what verify_against_dispatch() below now does.
    for i, (name, params, _h) in enumerate(cmds):
        args[i] = len(params)
    for row in range(0, 256, 16):
        vals = " ".join("$%02X" % a for a in args[row:row + 16])
        out.append("                fcb     " + ",".join("$%02X" % a for a in args[row:row + 16])
                   + "        ; %02X-%02X" % (row, row + 15))

    # -- test argument counts ---------------------------------------------------------
    out.append("")
    out.append("* -- VMTEST_ARGS: operand bytes per TEST opcode --------------------")
    out.append("* * vm_skip_instruction steps ip by this after a test runs. Duplicating")
    out.append("* these lengths in the assembly would be a second place to drift.")
    out.append("VMTEST_ARGS:")
    targs = [0] * 256
    for i, (name, params, _h) in enumerate(tests):
        targs[i] = len(params)
    for row in range(0, 256, 16):
        out.append("                fcb     "
                   + ",".join("$%02X" % a for a in targs[row:row + 16])
                   + "        ; %02X-%02X" % (row, row + 15))

    # ── command handler table ──────────────────────────────────────────────────────────
    out.append("\n* ── VMOP_TAB: handler per command opcode ──────────────────────────")
    out.append("* ★★ Unimplemented entries point at vm_op_unimpl, which HALTS with the opcode")
    out.append("* number. AC-5 forbids a silent no-op: it would desynchronise nothing and")
    out.append("* diverge everything, so the diff would name a symptom, never the cause.")
    out.append("VMOP_TAB:")
    miss_cmd = []
    for i in range(256):
        if i == 0:
            out.append("                fdb     vm_op_return            ; 00 return")
            continue
        if i < len(cmds):
            name, params, handler = cmds[i]
            base = label_for(handler)
            lab = "vmop_" + base if base else None
            st = status.get(("cmd", i), "unimplemented")
            if lab and lab in implemented:
                out.append("                fdb     %-23s ; %02X %s(%s)" % (lab, i, name, params))
            elif st == "modelled":
                # ★ declared no-op: consumes its arguments, changes nothing the diff observes
                out.append("                fdb     vm_op_modelled          ; %02X %s(%s)  [modelled]"
                           % (i, name, params))
            else:
                miss_cmd.append((i, name, lab or "(oracle: unbound)"))
                out.append("                fdb     vm_op_unimpl            ; %02X %s(%s)"
                           % (i, name, params))
        else:
            out.append("                fdb     vm_op_unimpl            ; %02X --" % i)

    # ── test handler table ─────────────────────────────────────────────────────────────
    out.append("\n* ── VMTEST_TAB: handler per test opcode ───────────────────────────")
    # ★★★★★ SIZED TO THE OPCODE SPACE, NOT TO 256, AND THAT IS WHERE P3b's 189 BYTES CAME FROM.
    # The v2 test space is 20 opcodes. This table used to emit 256 entries so the dispatch could
    # index with a raw opcode byte and never range-check -- entries 20-255 were all
    # vm_test_unimpl, which is 472 bytes of padding whose only job was to make an out-of-range
    # opcode land somewhere safe.
    # ★★★★ vm_core.s now does that job with `cmpa #VMTEST_MAX / bhs vm_test_unimpl`. **The
    # behaviour is identical**: an opcode >= 20 reached vm_test_unimpl through the table before
    # and reaches it through the check now, same handler, same halt, same reported opcode.
    # ★★★ It is also more honest about the opcode space -- a 256-entry table asserts that 256
    # test opcodes exist, and 20 do [CLAUDE.md 2H: verify what a number COUNTS].
    # ★★ VMOP_ARGS, VMTEST_ARGS and VMOP_TAB are deliberately LEFT AT 256 for now: one change,
    # measured on its own [L-54]. VMOP_TAB's space is 183 of 256 so the padding is small; the
    # two ARGS tables are byte-wide and would save 73 and 236, and each needs its own check.
    out.append("VMTEST_MAX      equ     %d" % len(tests))
    out.append("VMTEST_TAB:")
    miss_test = []
    for i in range(len(tests)):
        if 1 <= i < len(tests):
            name, params, handler = tests[i]
            base = label_for(handler)
            lab = "vmtest_" + base if base else None
            if lab and lab in implemented:
                out.append("                fdb     %-23s ; %02X %s(%s)" % (lab, i, name, params))
            else:
                miss_test.append((i, name, lab or "(oracle: unbound)"))
                out.append("                fdb     vm_test_unimpl          ; %02X %s(%s)"
                           % (i, name, params))
        else:
            out.append("                fdb     vm_test_unimpl          ; %02X --" % i)

    return "\n".join(out) + "\n", miss_cmd, miss_test


def verify_against_dispatch():
    """★★★ Check the opcode->name mapping this generator emits against dispatch.py's own table.

    The generator reads the same list dispatch.py reads, so this cannot catch a bad SOURCE --
    but it does catch a bad INDEX BASE, which is exactly the error the first draft made and
    which no amount of "generate, do not type" would have prevented.
    """
    from agivm.dispatch import DispatchTable
    d = DispatchTable(0x2917)
    bad = []
    for i, (name, params, _h) in enumerate(optable.V2_COMMANDS):
        got = d.commands[i]
        if got is None or got.name != name or got.num != i:
            bad.append(("cmd", i, name, got.name if got else None))
    for i, (name, params, _h) in enumerate(optable.V2_TESTS):
        got = d.tests[i]
        if got is None or got.name != name or got.num != i:
            bad.append(("test", i, name, got.name if got else None))
    return bad


def implemented_labels(src_dir):
    """Every vmop_/vmtest_ label the assembly actually defines."""
    found = set()
    for p in pathlib.Path(src_dir).glob("vm_*.s"):
        if p.name == "vm_tables.s":
            continue
        for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"^(vm(?:op|test)_\w+):", line)
            if m:
                found.add(m.group(1))
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="")
    ap.add_argument("--src", default=str(ROOT / "src" / "harness"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    bad = verify_against_dispatch()
    if bad:
        print("★★★ INDEXING CHECK FAILED -- generator disagrees with dispatch.py:")
        for kind, i, want, got in bad[:8]:
            print(f"   {kind} 0x{i:02X}: table says {want!r}, dispatch says {got!r}")
        return 1
    print(f"indexing check: OK -- {len(optable.V2_COMMANDS)} commands and "
          f"{len(optable.V2_TESTS)} tests agree with dispatch.py, index == opcode")

    impl = implemented_labels(a.src)
    st = statuses()
    text, miss_cmd, miss_test = build(impl, st)

    print(f"handlers defined in {a.src}: {len(impl)}")
    print(f"commands wired: {len(optable.V2_COMMANDS) - len(miss_cmd)} of "
          f"{len(optable.V2_COMMANDS)}   tests wired: "
          f"{len(optable.V2_TESTS) - len(miss_test)} of {len(optable.V2_TESTS)}")

    if a.check:
        target = pathlib.Path(a.out or (ROOT / "src" / "harness" / "vm_tables.s"))
        if not target.exists():
            print(f"CHECK FAILED: {target} does not exist")
            return 1
        cur = target.read_text(encoding="utf-8")
        if cur != text:
            print(f"CHECK FAILED: {target} differs from the generated table.")
            print("  -> regenerate with --out, and do not hand-edit it.")
            return 1
        print(f"CHECK OK: {target} matches optable.py.")
        return 0

    if a.out:
        p = pathlib.Path(a.out)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {p}  ({len(text)} bytes)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
