#!/usr/bin/env python3
"""harness/tools/pc_manifest.py -- AC-4: one manifest row per PC/DOS title.

★★ THIS TOOL EXISTS BECAUSE THE LAST ONE DID NOT. games/manifests/pc-agi.tsv says in its own
header that it was "generated at P1.1 by scratch tooling" -- so the rows were reproducible only
by someone who still had the scratch script. L-45: an unsaved analysis script cannot be audited,
and the act of saving it is itself a check. Regenerating the file needed the tool to exist, so
here it is.

★★ MANIFEST ONLY (§2P). Checksums, counts and sizes identify a release exactly; no resource
byte, no game text and no game file ever enters the repository.

★ Columns match the existing pc-agi.tsv so the file's shape is unchanged and a diff against the
previous version is readable -- the point of regenerating is to ADD the new titles, not to
reformat the held ones.
"""
import argparse
import hashlib
import io
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

from volread import resource  # noqa: E402

TYPES = ["LOGIC", "PICTURE", "VIEW", "SOUND"]
V2_DIRS = {"logdir", "picdir", "viewdir", "snddir"}

HEADER = """\
# PC/DOS AGI MANIFEST -- generated by harness/tools/pc_manifest.py.
# ★ MANIFEST ONLY. No game data is in this repository and none ever may be (§2P).
# shape: 'AGI v2' directories are parsed; 'AGI v3' are recorded and NOT parsed (LZW, §11.1);
#        'SCI' are recorded and NOT parsed (design §1.1).
# res_* are resources PRESENT (not slots). slots_* are DIR length / 3, an upper bound.
# sha256 columns are of the named FILE, so a release can be identified exactly.
#
"""
COLS = ["dir", "shape", "files", "bytes", "logdir_sha256", "object_sha256", "words_sha256",
        "res_logic", "res_picture", "res_view", "res_sound",
        "slots_logic", "slots_picture", "slots_view", "slots_sound",
        "vol_count", "vol_bytes", "res_bytes"]


def find_ci(d, name):
    for p in d.iterdir():
        if p.is_file() and p.name.lower() == name:
            return p
    return None


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest() if p else ""


def shape_of(names):
    if V2_DIRS <= names:
        return "AGI v2"
    if any(n.startswith("resource.") for n in names):
        return "SCI"
    if any(n.endswith("dir") for n in names) and any("vol." in n for n in names):
        return "AGI v3"
    return "unknown"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=r"C:\Projects\agi-games\pc")
    ap.add_argument("--out", default=str(ROOT / "games" / "manifests" / "pc-agi.tsv"))
    a = ap.parse_args()

    root = pathlib.Path(a.root)
    rows = []
    for d in sorted((p for p in root.iterdir() if p.is_dir()), key=lambda x: x.name.lower()):
        files = [f for f in d.rglob("*") if f.is_file()]
        names = {f.name.lower() for f in d.iterdir() if f.is_file()}
        shape = shape_of(names)
        r = {c: "" for c in COLS}
        r["dir"] = d.name
        r["shape"] = shape
        r["files"] = len(files)
        r["bytes"] = sum(f.stat().st_size for f in files)

        if shape == "AGI v2":
            g = resource.load_from_files(str(d))
            r["logdir_sha256"] = sha(find_ci(d, "logdir"))
            r["object_sha256"] = sha(find_ci(d, "object"))
            r["words_sha256"] = sha(find_ci(d, "words.tok"))
            counts = g.counts()
            for t in TYPES:
                present, slots = counts[t]
                r["res_" + t.lower()] = present
                r["slots_" + t.lower()] = slots
            vols = [f for f in d.iterdir()
                    if f.is_file() and f.name.lower().startswith("vol.")]
            r["vol_count"] = len(vols)
            r["vol_bytes"] = sum(f.stat().st_size for f in vols)
            total = 0
            for t in TYPES:
                for e in g.dirs[t]:
                    if not e.present:
                        continue
                    try:
                        total += len(g.load(t, e.index))
                    except Exception:                          # noqa: BLE001
                        pass          # a malformed entry; corpus_fetch_check.py reports them
            r["res_bytes"] = total
        elif shape == "AGI v3":
            vols = [f for f in d.iterdir()
                    if f.is_file() and "vol." in f.name.lower()]
            r["vol_count"] = len(vols)
            r["vol_bytes"] = sum(f.stat().st_size for f in vols)
            dirf = [f for f in d.iterdir()
                    if f.is_file() and f.name.lower().endswith("dir")]
            if dirf:
                r["logdir_sha256"] = sha(dirf[0])
        rows.append(r)

    out = pathlib.Path(a.out)
    with out.open("w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        f.write("\t".join(COLS) + "\n")
        for r in rows:
            f.write("\t".join(str(r[c]) for c in COLS) + "\n")

    byshape = {}
    for r in rows:
        byshape[r["shape"]] = byshape.get(r["shape"], 0) + 1
    print("wrote %s" % out)
    print("rows: %d   %s" % (len(rows), byshape))
    print()
    print("%-24s %-7s %6s %10s %10s" % ("dir", "shape", "vols", "vol_bytes", "res_bytes"))
    for r in rows:
        print("%-24s %-7s %6s %10s %10s"
              % (r["dir"], r["shape"], r["vol_count"], r["vol_bytes"], r["res_bytes"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
