#!/usr/bin/env python3
"""harness/tools/vm_coverage.py -- AC-5: what the gate EXERCISES, against what the corpus HAS.

★★★ THREE NUMBERS, AND THEY ANSWER THREE DIFFERENT QUESTIONS. CLAUDE.md 2H's worked example is
the "319 opcodes" figure: exactly correct and meaning something other than what quoting it
implies. The same trap is live here, so this tool prints all three and labels them:

  PRESENT   -- opcodes any LOGIC in the 9-title corpus contains  (the static census, 181)
  UNIVERSAL -- opcodes present in ALL NINE titles                (98)
  EXERCISED -- opcodes the 6809 actually DISPATCHED in this run  (measured here)

★★ EXERCISED is the only one this tool measures; the other two are read from the census, which
opcode_census.py generated by WALKING the bytecode rather than histogramming it. A gate can only
check what it runs, and "implemented" is a fourth thing again -- read from vm_tables.s, because
a handler bound to vm_op_unimpl is a declared hole and a handler bound to vm_op_modelled is a
declared no-op. Both are listed rather than counted as coverage.

★★★ COMMANDS AND TESTS ARE SEPARATE OPCODE SPACES. Test $01 (equaln) and command $01 (increment)
are different instructions. Counting them in one pool is the error 2H names.

★ 2N.1's rule applies: this REPORTS. It does not gate a build.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from agivm import optable  # noqa: E402


def read_seen(path):
    counts = {}
    if not path.exists():
        return counts
    for line in path.read_text(errors="replace").splitlines():
        f = line.split()
        if len(f) == 2:
            counts[int(f[0], 16)] = int(f[1])
    return counts


def binding(tables_text, kind, op):
    """What vm_tables.s binds this opcode to: a handler, vm_op_unimpl, or vm_op_modelled."""
    tag = "; %02X " % op
    section = tables_text.split("VMTEST_TAB")[1 if kind == "test" else 0]
    for line in section.splitlines():
        if tag in line and "fdb" in line:
            m = re.search(r"fdb\s+(\S+)", line)
            if m:
                return m.group(1)
    return "?"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sweeps", default="build/vm_sweep")
    ap.add_argument("--census", default="docs/project/opcode-census.md")
    a = ap.parse_args()

    sweeps = sorted(p for p in pathlib.Path(a.sweeps).iterdir() if p.is_dir())
    cmd_seen, test_seen, titles = {}, {}, []
    for d in sweeps:
        c = read_seen(d / "opseen.txt")
        t = read_seen(d / "testseen.txt")
        if not c:
            continue
        titles.append(d.name)
        for op, n in c.items():
            cmd_seen[op] = cmd_seen.get(op, 0) + n
        for op, n in t.items():
            test_seen[op] = test_seen.get(op, 0) + n

    cmd_ex = {op for op, n in cmd_seen.items() if n}
    test_ex = {op for op, n in test_seen.items() if n}

    tables = (ROOT / "src/harness/vm_tables.s").read_text(errors="replace")

    print("titles measured : %d  (%s)" % (len(titles), ", ".join(titles)))
    print()
    print("                          commands   tests   total")
    print("  EXERCISED by the gate   %8d %7d %7d"
          % (len(cmd_ex), len(test_ex), len(cmd_ex) + len(test_ex)))

    # the census's own totals, quoted rather than recomputed
    census = pathlib.Path(a.census)
    census_text = census.read_text(errors="replace") if census.exists() else ""
    for line in census_text.splitlines():
        if line.startswith("| **present in the corpus**") or \
           line.startswith("| present in ALL 9 titles"):
            print("  census: %s" % line.strip())
    print()

    # ★★ THE NUMBER AC-5 ACTUALLY ASKS FOR: of the opcodes the census found in ALL NINE titles,
    # how many did the gate dispatch? "Present in the corpus" includes opcodes carried by a
    # single title; the UNIVERSAL set is the one every game depends on, so a hole there is a
    # different severity from a hole in the tail. Parsed from the census's own common-set
    # section rather than recomputed, so the two documents cannot disagree (§2F).
    common = {"command": set(), "test": set()}
    section = census_text.split("## Common set")[-1].split("##")[0] if census_text else ""
    kind = None
    for line in section.splitlines():
        if line.startswith("**Commands"):
            kind = "command"
        elif line.startswith("**Tests"):
            kind = "test"
        elif kind and line.startswith("`0x"):
            common[kind].update(int(m, 16) for m in re.findall(r"`0x([0-9A-Fa-f]{2})`", line))
    for kind, seen in (("command", cmd_ex), ("test", test_ex)):
        u = common[kind]
        if not u:
            continue
        hit = u & seen
        print("  UNIVERSAL %-8s (present in all 9 titles): %d of %d dispatched"
              % (kind, len(hit), len(u)))
        miss = sorted(u - seen)
        if miss:
            names = ", ".join("%02X %s" % (op, (optable.V2_COMMANDS if kind == "command"
                                                else optable.V2_TESTS)[op][0]) for op in miss)
            print("      not dispatched: %s" % names)
    print()

    # ── what is PRESENT but never dispatched ────────────────────────────────────────────
    for kind, table, seen in (("command", optable.V2_COMMANDS, cmd_ex),
                              ("test", optable.V2_TESTS, test_ex)):
        # ★ V2_COMMANDS / V2_TESTS are LISTS indexed by opcode, not dicts. Entry 0 of the test
        # list is condUnknown, a placeholder, and entries with an empty name are gaps.
        holes = []
        for op, entry in enumerate(table):
            name = entry[0] if isinstance(entry, tuple) else str(entry)
            if not name or name in ("unknown", "--"):
                continue
            if op in seen:
                continue
            holes.append((op, name, binding(tables, kind, op)))
        print("%s opcodes NOT dispatched in this run: %d" % (kind, len(holes)))
        unimpl = [h for h in holes if "unimpl" in h[2]]
        print("  of which bound to vm_%s_unimpl (a declared HOLE): %d"
              % ("op" if kind == "command" else "test", len(unimpl)))
        for op, name, b in unimpl[:40]:
            print("      %02X %-22s %s" % (op, name, b))
        if len(unimpl) > 40:
            print("      ... and %d more" % (len(unimpl) - 40))
        print()

    # ★ the inverse check, which is the one that can contradict me: anything dispatched that
    # the tables say is unimplemented would mean the halt did not fire.
    bad = [op for op in sorted(cmd_ex) if "unimpl" in binding(tables, "command", op)]
    print("dispatched while bound to vm_op_unimpl: %d %s"
          % (len(bad), "★★★ " + repr(bad) if bad else "(as expected: the halt fires instead)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
